"""
memguard._report
~~~~~~~~~~~~~~~~
MemGuardReport dataclass and the terminal pretty-printer.

The report object is the single source of truth produced by every
profiling run (decorator, context manager, or manual).  It is also
what gets serialised to JSON when export_json is requested.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from ._colors import BOLD, CYAN, DIM, GREEN, MAGENTA, RED, YELLOW
from ._constants import DEFAULT_THRESHOLD_MB, LEAK_OBJECT_THRESHOLD, REPORT_WIDTH


# ── Dataclass ────────────────────────────────────────────────────────────────

class MemGuardReport:
    """
    Holds every measurement and analysis result for one profiled call.

    Attributes
    ----------
    func_name : str
        Fully-qualified name of the profiled callable or block label.
    label : str
        Optional human-readable tag supplied by the caller.
    timestamp : str
        ISO-8601 timestamp of when the call started.
    duration_s : float
        Wall-clock time of the wrapped call in seconds.
    mem_before_mb : float
        tracemalloc current usage just *before* the call (MB).
    mem_after_mb : float
        tracemalloc current usage just *after* the call (MB).
    peak_mb : float
        tracemalloc peak usage recorded *during* the call (MB).
    net_mb : float
        ``mem_after_mb - mem_before_mb`` — the headline leak signal.
    top_stats : list[dict]
        Top allocation sites from the tracemalloc snapshot diff.
    object_delta : dict[str, tuple[int, int, int]]
        Mapping of ``type_name -> (before_count, after_count, delta)``
        for every gc-tracked type that changed during the call.
    leaked_types : list[str]
        Human-readable strings for types whose delta exceeded
        ``LEAK_OBJECT_THRESHOLD``.
    suggestions : list[str]
        Free-text analysis bullets generated by the suggestion engine.
    exception : str | None
        Formatted traceback if the wrapped function raised, else None.
    call_index : int
        1-based sequential index for repeated calls to the same function.
    """

    __slots__ = (
        "func_name", "label", "timestamp", "duration_s",
        "mem_before_mb", "mem_after_mb", "peak_mb", "net_mb",
        "top_stats", "object_delta", "leaked_types",
        "suggestions", "exception", "call_index",
    )

    def __init__(self, func_name: str, label: str) -> None:
        self.func_name:     str             = func_name
        self.label:         str             = label
        self.timestamp:     str             = datetime.now().isoformat()
        self.duration_s:    float           = 0.0
        self.mem_before_mb: float           = 0.0
        self.mem_after_mb:  float           = 0.0
        self.peak_mb:       float           = 0.0
        self.net_mb:        float           = 0.0
        self.top_stats:     list[dict]      = []
        self.object_delta:  dict            = {}
        self.leaked_types:  list[str]       = []
        self.suggestions:   list[str]       = []
        self.exception:     str | None      = None
        self.call_index:    int             = 0

    # ── Serialisation ────────────────────────────────────────────────────────

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable dictionary of the report."""
        return {
            "func_name":     self.func_name,
            "label":         self.label,
            "timestamp":     self.timestamp,
            "call_index":    self.call_index,
            "duration_s":    round(self.duration_s, 6),
            "mem_before_mb": round(self.mem_before_mb, 6),
            "mem_after_mb":  round(self.mem_after_mb, 6),
            "peak_mb":       round(self.peak_mb, 6),
            "net_mb":        round(self.net_mb, 6),
            "leaked_types":  self.leaked_types,
            "suggestions":   self.suggestions,
            "exception":     self.exception,
            "top_stats":     self.top_stats[:5],
        }

    def to_json(self, indent: int = 2) -> str:
        """Serialise the report to a JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    def save_json(self, path: str) -> None:
        """Write the JSON report to *path*."""
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(self.to_json())


# ── Pretty printer ───────────────────────────────────────────────────────────

def print_report(report: MemGuardReport, verbose: bool, top_n: int) -> None:
    """Render *report* to stdout with full ANSI formatting."""
    W    = REPORT_WIDTH
    sep  = BOLD(DIM("─" * W))
    sep2 = BOLD(DIM("═" * W))

    tag = f"[MemGuard] {report.func_name}"
    if report.label:
        tag += f" ({report.label})"
    tag += f"  •  call #{report.call_index}"

    print()
    print(sep2)
    print(BOLD(CYAN(f"  🔍  {tag}")))
    print(BOLD(DIM(f"      {report.timestamp}")))
    print(sep2)

    # ── Memory summary ───────────────────────────────────────────────────────
    net_color = RED if report.net_mb > DEFAULT_THRESHOLD_MB else GREEN
    print(BOLD("  📊  MEMORY SUMMARY"))
    print(sep)
    print(f"  {'Before':20s}  {report.mem_before_mb:>10.4f} MB")
    print(f"  {'After':20s}  {report.mem_after_mb:>10.4f} MB")
    print(f"  {'Peak':20s}  {YELLOW(f'{report.peak_mb:>10.4f} MB')}")
    print(f"  {net_color(f'Net Growth           {report.net_mb:>+10.4f} MB')}")
    print(f"  {'Wall Time':20s}  {report.duration_s:>10.4f} s")

    # ── Object delta ─────────────────────────────────────────────────────────
    if verbose and report.object_delta:
        changed = sorted(
            report.object_delta.items(),
            key=lambda x: abs(x[1][2]),
            reverse=True,
        )[:top_n]
        print()
        print(BOLD("  🧬  OBJECT DELTA  (gc-tracked types with count change)"))
        print(sep)
        print(f"  {'Type':<30s} {'Before':>8s}  {'After':>8s}  {'Delta':>8s}")
        print(sep)
        for name, (b, a, d) in changed:
            d_str = f"{d:>+8d}"
            if d > LEAK_OBJECT_THRESHOLD:
                d_colored = RED(d_str)
            elif d > 10:
                d_colored = YELLOW(d_str)
            elif d < 0:
                d_colored = GREEN(d_str)
            else:
                d_colored = d_str
            print(f"  {name:<30s} {b:>8d}  {a:>8d}  {d_colored}")

    # ── Top allocation sites ─────────────────────────────────────────────────
    if verbose and report.top_stats:
        n = min(top_n, len(report.top_stats))
        print()
        print(BOLD(f"  📍  TOP {n} ALLOCATION SITES  (tracemalloc diff)"))
        print(sep)
        print(f"  {'File:Line':<52s} {'Size':>10s}  {'Count':>8s}")
        print(sep)
        for s in report.top_stats[:top_n]:
            loc = f"{s['file']}:{s['line']}"
            if len(loc) > 52:
                loc = "…" + loc[-51:]
            size_str = s["size"]
            if s["size_b"] > 1_000_000:
                size_str = RED(size_str)
            elif s["size_b"] > 100_000:
                size_str = YELLOW(size_str)
            print(f"  {loc:<52s} {size_str:>10s}  {s['count']:>8d}")

    # ── Leaked types ─────────────────────────────────────────────────────────
    if report.leaked_types:
        print()
        print(BOLD(RED("  ⚠️   LEAK CANDIDATES")))
        print(sep)
        for lt in report.leaked_types:
            print(f"  {RED('●')} {lt}")

    # ── Suggestions ──────────────────────────────────────────────────────────
    print()
    print(BOLD("  💡  ANALYSIS & SUGGESTIONS"))
    print(sep)
    for tip in report.suggestions:
        is_critical = any(k in tip for k in ("LEAK", "GROWTH", "TREND", "HOTSPOT"))
        is_warn     = any(k in tip for k in ("CHURN", "SLOW"))
        icon = RED("⛔") if is_critical else (YELLOW("⚡") if is_warn else GREEN("✔"))
        # Word-wrap at 62 chars
        words, lines, cur = tip.split(), [], ""
        for w in words:
            if len(cur) + len(w) + 1 > 62:
                lines.append(cur)
                cur = w
            else:
                cur = (cur + " " + w).strip()
        if cur:
            lines.append(cur)
        for i, line in enumerate(lines):
            print(f"  {icon}  {line}" if i == 0 else f"      {line}")

    # ── Exception ────────────────────────────────────────────────────────────
    if report.exception:
        print()
        print(BOLD(RED("  ❌  EXCEPTION DURING CALL")))
        print(sep)
        for line in report.exception.strip().splitlines():
            print(f"  {RED(line)}")

    print(sep2)
    print()